'use strict';
(()=>{
const $=id=>document.getElementById(id),t=(k,v)=>DMI18N.t(k,v),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let config=DMStore.loadSettings(),game=new Champ.Game(),playing=false,screen='menu',origin='menu',selected=null,camera=0,gesture=null,tool=null,battle=null,albumPage=0,ownedOnly=false,dexSelected=null,tutorialPage=0,tutorialReturn='menu',netplayReturn=null,confirmState=null,deleting=null,fx=null;
const DRAG_GAIN=1.55,PET_DRAG_GAIN=1.35,EDGE_PAN_SPEED=420;
const unitVolume=(v,fallback=.1)=>{v=Number(v);return Number.isFinite(v)?Math.max(0,Math.min(1,v)):fallback;};config.volume=unitVolume(config.volume);config.sfxVolume=unitVolume(config.sfxVolume);
let cache=DMStore.loadCache();if(cache&&game.valid(cache))game.load(cache);else cache=null;
DMI18N.set(config.lang);const images={};for(const k of ['meat','med']){images[k]=new Image();images[k].src='assets/'+k+'.png';images[k].onerror=()=>{images[k].onerror=null;images[k].src=CHAMP_ITEMS[k];};}images.egg=new Image();images.egg.src='assets/egg-icon.png';
const eggImages=Champ.eggs.map((e,i)=>{const a=new Image();a.src='assets/egg-'+i+'.png';return a;});const eggImage=p=>eggImages[Champ.eggs.findIndex(e=>e.id===p.eggId)]||images.egg;
const music={menu:new Audio('assets/menu.mp3'),game:new Audio('assets/game.mp3'),battle:new Audio('assets/battle.mp3'),victory:new Audio('assets/victory.mp3'),lose:new Audio('assets/lose.mp3')};for(const a of Object.values(music)){a.loop=true;a.volume=unitVolume(config.volume);}let musicStarted=false,musicMode='menu',fade=1,fadeStart=0,audioContext=null;
music.victory.loop=music.lose.loop=false;for(const k of ['victory','lose'])music[k].onended=()=>{if(musicMode===k)musicSwitch('game');};
function sound(evolve=false){try{const v=Number(config.sfxVolume??.1);if(!v)return;audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();(evolve?[523,659,784,1047]:[660]).forEach((hz,i)=>{const a=audioContext.currentTime+i*.12,o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(v*.15,a);g.gain.exponentialRampToValueAtTime(.001,a+.12);o.connect(g);g.connect(audioContext.destination);o.start(a);o.stop(a+.13);});}catch{}}
function musicSwitch(mode,reset=false){if(mode!==musicMode){for(const k of ['battle','victory','lose']){music[k].pause();music[k].currentTime=0;}}if(reset){music.menu.currentTime=0;fade=0;fadeStart=performance.now();}musicMode=mode;for(const [key,a]of Object.entries(music)){a.volume=unitVolume(unitVolume(config.volume)*(key==='menu'?fade:1),0);if(key===mode&&musicStarted&&a.volume>0)a.play().catch(()=>{});else a.pause();}}
document.addEventListener('pointerdown',()=>{if(!musicStarted){musicStarted=true;musicSwitch(musicMode);}},{once:true});document.addEventListener('click',e=>{if(e.target.closest('button:not(:disabled)'))sound();});
let noticeEnd=0,noticeText='';function notice(key,vars={}){noticeText=t(key,vars);$('notice').textContent=noticeText;$('notice').style.opacity=1;noticeEnd=performance.now()+5000;const old=$('panel-notice');if(old)old.remove();if(screen!=='home'){const p=document.createElement('p');p.id='panel-notice';p.className='warning';p.setAttribute('role','status');p.textContent=t(key,vars);$('panel-content').prepend(p);}}
const btn=(id,key,cls='',disabled=false)=>`<button id="${id}" class="${cls}" ${disabled?'disabled':''}>${esc(t(key))}</button>`;
const on=(id,fn)=>{const e=$(id);if(e)e.onclick=fn;};
const fmt=s=>{s=Math.max(0,Math.floor(s));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0');};
const petName=p=>p.speciesId===null?'Digi-Egg':Champ.catalog[p.speciesId].name;
const stageName=p=>['Digi-Egg','Baby I','Baby II','Rookie','Champion','Ultimate','Mega','Ultra'][Champ.stage(p)];
const dexStageName=stage=>t(['','stageBabyI','stageBabyII','stageRookie','stageChampion','stageUltimate','stageMega','stageUltra'][stage]||'stage');
const bar=(value,cls='')=>`<div class="meter ${cls}"><i style="width:${Math.max(0,Math.min(100,value))}%"></i></div>`;
const petSelected=()=>game.get(selected)||game.s.pets[0];
function save(){if(!playing&&!cache)return;const state=game.export();if(DMStore.saveCache(state))cache=state;else notice('saveFailed');}
function updateTips(){const ps=game.s.pets.filter(p=>Champ.hints(p));$('tips').disabled=!playing||!ps.length||!!(battle&&!battle.done);$('tips').textContent=t('tips');}on('tips',()=>{if($('tips').disabled)return;screen='tips';panel('tips',game.s.pets.filter(p=>Champ.hints(p)).map(p=>{const h=Champ.hints(p);return `<article class="card"><h3>${esc(petName(p))}</h3><p>${esc(t(h.kind,{name:petName(p),stat:h.stats.map(k=>t(k)).join(' / ')}))}</p></article>`;}).join(''));layout();});
function layout(){$('device').dataset.screen=screen;$('device').dataset.origin=origin;document.documentElement.lang=config.lang==='pt'?'pt-BR':'en-US';$('rotate-title').textContent=t('rotateTitle');$('rotate-text').textContent=t('rotateText');updateTips();const names=['home','status','eggs','album','colosseum','netplay','settings'];const labels=['nursery','status','eggs','album','colosseum','netplay','settings'];$('navigation').innerHTML=names.map((n,i)=>btn('nav-'+n,labels[i],(screen===n||n==='album'&&screen==='album-detail')?'active':'',!playing&&['home','status','eggs','colosseum','netplay'].includes(n))).join('');names.forEach(n=>on('nav-'+n,()=>{if(battle&&!battle.done)return;if(n==='netplay')netplayReturn=null;if(screen===n){show(origin==='menu'?'menu':'home');}else show(n);}));$('language').textContent=config.lang==='pt'?'EN-US / [PT-BR]':'[EN-US] / PT-BR';$('language').setAttribute('aria-checked',String(config.lang==='pt'));$('tutorial').textContent=t('tutorial');$('tutorial').disabled=screen==='battle'||!!confirmState;$('main-menu').textContent=t('mainMenu');$('main-menu').disabled=!!(battle&&!battle.done);$('save-exit').textContent=t('saveExit');$('save-exit').disabled=!playing||!!(battle&&!battle.done);$('footer-note').textContent=t(playing?'localSave':'collection');}
function panel(title,html){$('habitat').hidden=true;$('panel').hidden=false;$('panel-title').textContent=t(title);$('back').textContent=t('back');$('back').hidden=screen==='menu'||screen==='battle';$('panel-content').innerHTML=html;if(performance.now()<noticeEnd&&noticeText){const n=document.createElement('p');n.id='panel-notice';n.className='warning';n.textContent=noticeText;$('panel-content').prepend(n);}}
function show(view){if(['battle','victory','lose'].includes(musicMode))musicSwitch(view==='menu'||origin==='menu'?'menu':'game');if(screen==='home'||screen==='menu')origin=screen;screen=view;tool=null;gesture=null;if(view==='home'){playing=true;$('habitat').hidden=false;$('panel').hidden=true;musicSwitch('game');renderHUD();}else if(view==='menu'){if(peer.status!=='disconnected')disconnect();musicSwitch('menu',musicMode!=='menu');panel('menu',`<div class="title-art"><img src="assets/egg-icon.png" alt=""><h2>DIGITAL BEASTS<br>CHAMPIONSHIP</h2><p class="muted">${esc(t('subtitle'))}</p></div><div class="menu-grid">${btn('new','newGame','primary')}${btn('continue','continue','',!cache&&!playing)}${btn('load','loadSave')}${btn('menu-album','album')}${btn('menu-settings','settings','mobile-only')}${btn('menu-about','about')}<button id="menu-language" class="mobile-only" type="button"></button></div>`);on('new',()=>ask('confirmNew',()=>ask('confirmNew2',()=>{disconnect();game=new Champ.Game();playing=true;selected=null;camera=0;cache=null;show('eggs');},()=>show('menu')),()=>show('menu')));on('continue',()=>{playing=true;show('home');});on('load',()=>$('save-file').click());['album','about'].forEach(k=>on('menu-'+k,()=>show(k)));on('menu-settings',()=>show('settings'));const ml=$('menu-language');if(ml){ml.textContent=config.lang==='pt'?'EN-US / [PT-BR]':'[EN-US] / PT-BR';ml.onclick=toggleLanguage;}}else if(view==='status')status();else if(view==='eggs')eggMenu();else if(view==='album')album();else if(view==='album-detail'&&dexSelected!==null)digidexDetail(dexSelected);else if(view==='settings')settings();else if(view==='tutorial')tutorial();else if(view==='help'){tutorialReturn=origin;show('tutorial');}else if(view==='about')panel('about',`<div class="help"><h3>Digital Beasts Championship</h3><p>${esc(t('aboutText'))}</p></div>`);else if(view==='colosseum')colosseum();else if(view==='netplay')netMenu();layout();}
on('back',()=>{if(confirmState){const f=confirmState.no;confirmState=null;f();return;}if(screen==='album-detail'){show('album');return;}if(screen==='tutorial'){const dest=tutorialReturn||origin||'menu';tutorialReturn=null;show(dest);return;}if(screen==='netplay'&&netplayReturn){const dest=netplayReturn;netplayReturn=null;show(dest);return;}show(origin==='menu'?'menu':'home');});function toggleLanguage(){config.lang=config.lang==='pt'?'en':'pt';DMI18N.set(config.lang);DMStore.saveSettings(config);if(screen==='confirm'&&confirmState)ask(confirmState.key,confirmState.yes,confirmState.no);else if(screen==='battle')battlePanel();else if(screen==='tips')$('tips').click();else show(screen);}on('language',toggleLanguage);
on('tutorial',()=>{if($('tutorial').disabled)return;if(screen!=='tutorial')tutorialReturn=screen;show('tutorial');});
on('main-menu',()=>{if(battle&&!battle.done)return;if(playing)save();show('menu');});
on('save-exit',()=>{save();DMStore.download(game.export(),config);disconnect();playing=false;show('menu');});
$('save-file').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{const p=await DMStore.readFile(f);const candidate=new Champ.Game(p.state);disconnect();game=candidate;playing=true;selected=game.s.pets[0]?.instanceId;save();show('home');}catch{notice('invalidSave');}};
function ask(key,yes,no){confirmState={key,yes,no};screen='confirm';panel('confirm',`<div class="card"><p>${esc(t(key))}</p><div class="controls">${btn('yes','yes','danger')}${btn('no','no')}</div></div>`);on('yes',()=>{confirmState=null;yes();});on('no',()=>{confirmState=null;no();});layout();}
function deletePet(id){if(peer.room)return;ask('delete1',()=>ask('delete2',()=>{const p=game.get(id);if(!p)return;deleting={id,start:performance.now()};show('home');camera=Math.max(0,p.x-$('scene').width/2);},()=>show('status')),()=>show('status'));}
function renderHUD(){if(screen!=='home')return;$('zone-tabs').innerHTML=Champ.zones.map((z,i)=>btn('zone-'+i,z)).join('');Champ.zones.forEach((z,i)=>on('zone-'+i,()=>{camera=clampCamera(i*300+150-$('scene').width/2);}));$('tools').innerHTML=`<button id="tool-meat" data-tool="meat"><img src="assets/meat.png" alt="">${esc(t('meat'))}</button><button id="tool-med" data-tool="med"><img src="assets/med.png" alt="">${esc(t('medicine'))}</button><button id="tool-clean" data-tool="clean">▥ ${esc(t('clean'))}</button>`;document.querySelectorAll('[data-tool]').forEach(b=>{b.addEventListener('pointerdown',e=>startGesture(e,b.dataset.tool));});hudPets();}
function hudPets(){if(screen!=='home')return;$('pets').innerHTML=[0,1].map(i=>{const p=game.s.pets[i];return p?`<button id="pet-${i}" class="${p.instanceId===selected?'selected':''}"><span class="pet-title"><strong>${esc(petName(p))}</strong><span>${esc(stageName(p))}</span></span><div class="mobile-pet-stats mobile-only"><span>HP <b>${Champ.stats(p).hp}</b></span><span>TP <b>${Champ.stats(p).tp}</b></span></div><div class="meters"><span>${esc(t('hunger'))} ${Math.round(p.hunger)}${bar(p.hunger)}</span><span>${esc(t('fatigue'))} ${Math.round(p.fatigue)}${bar(p.fatigue,'fatigue')}</span></div></button>`:btn('pet-'+i,'emptySlot');}).join('');[0,1].forEach(i=>on('pet-'+i,()=>{const p=game.s.pets[i];if(p){selected=p.instanceId;camera=clampCamera(p.x-$('scene').width/2);hudPets();}else show('eggs');}));}
function status(){panel('status',`<div class="grid">${game.s.pets.map(p=>{const s=Champ.stats(p),st=Champ.stage(p),need=Champ.TIMES[st];return `<article class="card"><canvas class="portrait" data-pet="${p.instanceId}" width="180" height="90"></canvas><h3>${esc(petName(p))}</h3><p>${esc(stageName(p))} · ${esc(t(p.sick?'sick':p.injured?'injured':'healthy'))}</p>${Champ.STATS.map(k=>`<div class="stat-row"><span>${esc(t(k))}</span><strong>${s[k]} <small class="muted">/ ${Math.round(s[k]+(Champ.trainingCap(p,k)-p.training[k])*(k==='hp'?5:k==='tp'?2:1))}</small></strong></div>`).join('')}${[['hunger',Math.round(p.hunger)],['fatigue',Math.round(p.fatigue)],['age',fmt(p.totalAge)],['stageAge',fmt(p.stageAge)],['careMistakes',p.careMistakes],['wins',p.wins+'/'+p.battles]].map(([k,v])=>`<div class="stat-row"><span>${esc(t(k))}</span><b>${v}</b></div>`).join('')}<p>${esc(t('specialization'))}: ${Math.round(Champ.STATS.reduce((n,k)=>n+p.training[k],0))}/${Champ.budget(st)}</p><p class="muted">${need?esc(t(p.stageAge>=need?'evoReady':'evoWait'))+(p.stageAge<need?' '+fmt(need-p.stageAge):''):esc(t('finalStage'))}</p>${btn('delete-'+p.instanceId,'delete','danger',!!p.battleLock||!!peer.room)}</article>`;}).join('')}</div><p class="muted">${esc(t('specializationHelp'))}</p>`);for(const p of game.s.pets)on('delete-'+p.instanceId,()=>deletePet(p.instanceId));}
function eggCondition(e){const k={totalWins:'poolWins',album:'poolAlbum',colosseum:'poolRound',netWinsOrColosseum:'poolOnline',colosseumClear:'poolClear'}[e.metric]||'initial';return t(k,{n:e.metric==='colosseumClear'?Champ.catalog.length:e.need});}
function eggMenu(){game.refreshUnlocks();panel('eggs',`${game.s.pets.length>=2?`<p class="warning">${esc(t('fullSlots'))}</p>`:''}<div class="grid">${Champ.eggs.map((e,i)=>`<article class="card"><h3>${!e.unlocked&&game.s.unlockedEggs[i]?'★ ':''}</h3><img class="egg-preview" src="assets/egg-${i}.png" alt="Digi-Egg ${i+1}"><p>${esc(eggCondition(e))}</p>${btn('egg-'+i,game.s.unlockedEggs[i]?'unlocked':'locked','',!game.s.unlockedEggs[i]||game.s.pets.length>=2)}</article>`).join('')}</div>`);Champ.eggs.forEach((e,i)=>on('egg-'+i,()=>{const p=game.adopt(e.id);if(p){playing=true;selected=p.instanceId;save();show('home');}}));}
function album(){let ids=Champ.catalog.map(s=>s.id).filter(id=>!ownedOnly||game.s.album[id]);const pages=Math.max(1,Math.ceil(ids.length/12));albumPage=Math.max(0,Math.min(pages-1,albumPage));panel('album',`<div class="dex-toolbar"><label><input id="owned" type="checkbox" ${ownedOnly?'checked':''}> ${esc(t('owned'))} · ${game.s.album.reduce((a,b)=>a+b,0)}/${DM20_DATA.obtainableCount}</label><p class="muted dex-hint">${esc(t('dexHint'))}</p></div><div class="album-grid">${ids.slice(albumPage*12,albumPage*12+12).map(id=>{const owned=!!game.s.album[id],s=Champ.catalog[id];return `<article class="album-card ${owned?'registered':'dim'}" ${owned?`data-dex-id="${id}" role="button" tabindex="0" aria-label="${esc(t('dexOpen',{name:s.name}))}"`:'aria-disabled="true"'}><canvas data-species="${id}" width="72" height="72"></canvas><strong>${esc(s.name)}</strong><small>${esc(dexStageName(s.stage))} · ${esc(s.attribute)}</small>${DM20_DATA.jogressOnly.includes(id)?`<small>${esc(t('unused'))}</small>`:''}</article>`;}).join('')}</div><div class="pager">${btn('first','≪','',albumPage===0)}${btn('prev','‹','',albumPage===0)}<span>${albumPage+1}/${pages}</span>${btn('next','›','',albumPage===pages-1)}${btn('last','≫','',albumPage===pages-1)}</div>`);on('owned',()=>{ownedOnly=$('owned').checked;albumPage=0;album();});on('first',()=>{albumPage=0;album();});on('prev',()=>{albumPage--;album();});on('next',()=>{albumPage++;album();});on('last',()=>{albumPage=pages-1;album();});document.querySelectorAll('.album-card[data-dex-id]').forEach(card=>{const open=()=>{dexSelected=Number(card.dataset.dexId);show('album-detail');};card.onclick=open;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}};});}
function dexRange(kind,r){if(!r)return'';const a=r.min,b=r.max;if(a!==null&&b!==null&&a===b)return t('dex'+kind+'Exact',{n:a});if(a!==null&&b!==null)return t('dex'+kind+'Range',{min:a,max:b});if(a!==null)return t('dex'+kind+'Min',{n:a});return t('dex'+kind+'Max',{n:b});}
function dexRouteLines(r){const lines=[];if(r.minAge>0)lines.push(t('dexStageTime',{time:fmt(r.minAge)}));for(const q of r.training)lines.push(t('dexTraining',{stat:t(q.stat),value:q.valueMin,n:q.min}));if(r.care)lines.push(dexRange('Care',r.care));if(r.effort)lines.push(dexRange('Effort',r.effort));if(r.stageBattles)lines.push(t('dexBattles',{n:r.stageBattles}));if(r.stageWins)lines.push(t('dexWins',{n:r.stageWins}));if(r.winRatio)lines.push(t('dexWinRatio',{n:Math.round(r.winRatio*100)}));if(r.eggIds?.length){const nums=r.eggIds.map(id=>Champ.eggs.findIndex(e=>e.id===id)+1).filter(n=>n>0).join(', ');if(nums)lines.push(t('dexEggOrigin',{n:nums}));}return lines;}
function digidexDetail(id){if(!game.s.album[id]){show('album');return;}const info=Champ.evolutionRequirements(id),s=info?.species;if(!s){show('album');return;}let obtain='';if(info.hatch.length){obtain=`<section class="dex-routes"><h3>${esc(t('dexHowToObtain'))}</h3><div class="dex-hatches">${info.hatch.map(h=>`<article class="dex-route hatch-route"><img src="assets/egg-${h.eggIndex}.png" alt="Digi-Egg ${h.eggIndex+1}"><div><strong>${esc(t('dexEgg',{n:h.eggIndex+1}))}</strong><p>${esc(t('dexHatchChance',{n:Math.round(h.chance*100)}))}</p><p>${esc(t('dexHatchTime',{time:fmt(h.minAge)}))}</p></div></article>`).join('')}</div></section>`;}else if(info.routes.length){obtain=`<section class="dex-routes"><h3>${esc(t('dexEvolutionRequirements'))}</h3>${info.routes.map(r=>{const from=Champ.catalog[r.fromId],lines=dexRouteLines(r);return `<article class="dex-route"><h4>${esc(t('dexFrom',{name:from.name}))}</h4><p class="muted">${esc(dexStageName(from.stage))} → ${esc(s.name)}</p><ul>${lines.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`;}).join('')}</section>`;}else obtain=`<section class="dex-routes"><p class="warning">${esc(t('dexNoRoute'))}</p></section>`;screen='album-detail';panel('album',`<div class="dex-detail"><div class="dex-identity"><canvas data-species="${id}" width="112" height="112"></canvas><div><h3>${esc(s.name)}</h3><p>${esc(dexStageName(s.stage))} · ${esc(s.attribute)}</p><p class="muted">${esc(t('dexRegistered'))}</p></div></div>${obtain}${info.routes.some(r=>r.effort)?`<p class="muted dex-rule-note">${esc(t('dexEffortNote'))}</p>`:''}${info.routes.length?`<p class="muted dex-rule-note">${esc(t('dexPriorityNote'))}</p>`:''}</div>`);}

function settings(){panel('settings',`<p class="muted"><strong>Digital Beasts Championship · v0.4.9</strong></p><label>${esc(t('music'))}<input id="volume" type="range" min="0" max="100" value="${Math.round(config.volume*100)}"></label><label>${esc(t('sfxVolume'))}<input id="sfx" type="range" min="0" max="100" value="${Math.round((config.sfxVolume??.1)*100)}"></label><label>${esc(t('server'))}<input id="server-url" style="width:100%" value="${esc(config.server||DMNet.DEFAULT_URL)}"></label><p class="muted">${esc(t('serverHint'))}</p><div class="controls">${btn('settings-help','tutorial')}${btn('settings-menu','menu')}</div>`);$('volume').oninput=e=>{config.volume=Number(e.target.value)/100;DMStore.saveSettings(config);musicSwitch(musicMode);};$('sfx').oninput=e=>{config.sfxVolume=Number(e.target.value)/100;DMStore.saveSettings(config);};$('server-url').onchange=e=>{const v=e.target.value.trim();if(/^wss?:\/\//.test(v)){config.server=v;DMStore.saveSettings(config);disconnect();peer.url=v;}};on('settings-help',()=>{tutorialReturn='settings';show('tutorial');});on('settings-menu',()=>show('menu'));}
function tutorial(){const pages=globalThis.CHAMP_TUTORIAL?.[config.lang]||globalThis.CHAMP_TUTORIAL?.en||[];if(!pages.length){panel('tutorial','');return;}tutorialPage=Math.max(0,Math.min(pages.length-1,tutorialPage));const page=pages[tutorialPage],sections=(page.sections||[]).map(sec=>`<section class="tutorial-section"><h3>${esc(sec.heading)}</h3>${(sec.paragraphs||[]).map(x=>`<p>${esc(x)}</p>`).join('')}${sec.bullets?.length?`<ul>${sec.bullets.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</section>`).join(''),indexButtons=pages.map((x,i)=>`<button class="tutorial-index-button ${i===tutorialPage?'active':''}" data-tutorial-page="${i}"><span>${String(i+1).padStart(2,'0')}</span>${esc(x.short||x.title)}</button>`).join(''),options=pages.map((x,i)=>`<option value="${i}" ${i===tutorialPage?'selected':''}>${i+1}. ${esc(x.short||x.title)}</option>`).join('');panel('tutorial',`<div class="tutorial-shell"><aside class="tutorial-index"><h3>${esc(t('tutorialIndex'))}</h3><label class="tutorial-select-label"><span>${esc(t('tutorialPageJump'))}</span><select id="tutorial-page-select">${options}</select></label><div class="tutorial-index-list">${indexButtons}</div></aside><article class="tutorial-content"><p class="tutorial-page-count">${esc(t('tutorialPageCount',{n:tutorialPage+1,total:pages.length}))}</p><h2>${esc(page.title)}</h2><p class="tutorial-lead">${esc(page.lead)}</p>${sections}${page.note?`<p class="tutorial-note">${esc(page.note)}</p>`:''}<div class="tutorial-nav">${btn('tutorial-prev','tutorialPrevious','',tutorialPage===0)}<strong>${tutorialPage+1}/${pages.length}</strong>${btn('tutorial-next','tutorialNext','primary',tutorialPage===pages.length-1)}</div></article></div>`);document.querySelectorAll('[data-tutorial-page]').forEach(b=>b.onclick=()=>{tutorialPage=Number(b.dataset.tutorialPage);tutorial();});const sel=$('tutorial-page-select');if(sel)sel.onchange=e=>{tutorialPage=Number(e.target.value);tutorial();};on('tutorial-prev',()=>{tutorialPage--;tutorial();});on('tutorial-next',()=>{tutorialPage++;tutorial();});}
function fighterSelect(){return `<label>${esc(t('choosePet'))}<select id="fighter">${game.s.pets.map(p=>`<option value="${p.instanceId}" ${p.instanceId===petSelected()?.instanceId?'selected':''}>${esc(petName(p))} · ${esc(stageName(p))}</option>`).join('')}</select></label>`;}
function colosseum(){const s=Champ.colosseum[game.s.colosseum.round-1];panel('colosseum',`<div class="colosseum-layout"><div class="colosseum-fighter">${fighterSelect()}<p class="muted colosseum-help">${esc(t('needRookie'))}</p></div><div class="card colosseum-card"><canvas data-species="${s.id}" class="portrait" width="180" height="90"></canvas><div class="colosseum-info"><h3>${esc(t('round'))} ${game.s.colosseum.round}/${Champ.catalog.length} · ${esc(s.name)}</h3><p class="muted">${esc(t('best'))}: ${game.s.colosseum.best} · ${esc(t('clears'))}: ${game.s.colosseum.clears}</p></div><div class="colosseum-actions">${btn('fight','battle','primary',!game.canBattle(petSelected()?.instanceId))}${btn('reset-colosseum','resetColosseum','danger')}</div></div><div class="card colosseum-card colosseum-online-card mobile-only"><div class="colosseum-vs" aria-hidden="true">VS</div><div class="colosseum-info colosseum-online-info"><h3>${esc(t('netplay'))}</h3></div><div class="colosseum-actions colosseum-online-actions">${btn('mobile-online','netplay','primary')}</div></div></div>`);$('fighter').onchange=e=>{selected=e.target.value;colosseum();};on('mobile-online',()=>{netplayReturn='colosseum';show('netplay');});on('reset-colosseum',()=>ask('resetColosseum1',()=>ask('resetColosseum2',()=>{game.s.colosseum.round=1;save();show('colosseum');},()=>show('colosseum')),()=>show('colosseum')));on('fight',()=>{const p=petSelected();if(!game.canBattle(p?.instanceId))return;startBattle([game.fighter(p.instanceId),{species:s.id,stats:Champ.PROFILES[s.id].stats}],crypto.getRandomValues(new Uint32Array(1))[0],p.instanceId,'colosseum',0);});}
function startBattle(fighters,seed,id,mode,local,round=null){const p=game.get(id);if(!p)return;p.battleLock=true;musicSwitch('battle');battle={result:ChampBattle.fight(...fighters,seed,true,mode==='colosseum'?{colosseumRound:game.s.colosseum.round}:{}),id,mode,local,round,start:performance.now(),done:false,sent:false,recorded:false,index:0};screen='battle';battlePanel();layout();}
function battlePanel(){screen='battle';panel(battle.mode==='netplay'?'netplay':'colosseum',`<div class="battle-screen"><div class="battle-health" id="battle-health"></div><canvas id="arena" width="600" height="320"></canvas><div id="sudden-banner" hidden></div><div class="battle-log" id="battle-log"></div><div class="controls" id="battle-controls"></div></div>`);layout();if(battle.done)resultButtons();}
function finishBattle(winner){if(!battle||battle.recorded)return;battle.recorded=true;battle.done=true;musicSwitch(winner===battle.local?'victory':'lose');game.recordBattle(battle.id,winner===battle.local,battle.mode);save();resultButtons();layout();}
function resultButtons(){if(!battle)return;$('battle-log').textContent=t(battle.result.winner===battle.local?'victory':'defeat');$('battle-controls').innerHTML=battle.mode==='netplay'?btn('rematch','rematch','primary')+btn('room-back','back'):btn('battle-next','next','primary');on('battle-next',()=>{battle=null;show('colosseum');});on('room-back',()=>{battle=null;show('netplay');});on('rematch',rematch);}
function drawBattle(now){if(!battle||!$('arena'))return;const b=battle,index=Math.min(b.result.frames.length-1,Math.max(0,Math.floor((now-b.start)/100))),f=b.result.frames[index];b.index=index;const cv=$('arena'),w=Math.round(cv.clientWidth),h=Math.round(cv.clientHeight);if(cv.width!==w||cv.height!==h){cv.width=w;cv.height=h;}const c=cv.getContext('2d');c.imageSmoothingEnabled=false;ChampArt.arena(c,w,h,f.sudden);$('sudden-banner').hidden=!f.sudden;$('sudden-banner').textContent=t('suddenDeath');const order=[b.local,1-b.local];$('battle-health').innerHTML=order.map((i,slot)=>{const p=f.fighters[i],name=Champ.catalog[p.species].name,role=b.mode==='netplay'?(i===0?'hostRole':'challengerRole'):(slot===0?'youRole':'opponentRole');return `<div><strong>${esc(t(role))} · ${esc(name)}</strong>${bar(p.hp/p.stats.hp*100)}HP ${p.hp}/${p.stats.hp} · TP ${p.tp}/${p.stats.tp}</div>`;}).join('');const mobilePortrait=matchMedia('(max-width:720px) and (orientation:portrait)').matches,zoom=mobilePortrait?1.10:1,viewWidth=600/zoom,toLocalX=x=>b.local===0?x:600-x,targetLeft=Math.max(-60,Math.min(600-viewWidth+60,toLocalX(f.fighters[b.local].x)-viewWidth/2));b.cameraX=mobilePortrait?(Number.isFinite(b.cameraX)?b.cameraX+(targetLeft-b.cameraX)*.12:targetLeft):0;const mapX=x=>40+(toLocalX(x)-b.cameraX)/viewWidth*(w-80),mapY=y=>50+((b.local===0?y:355-y)-50)/240*(h-90),spriteScale=5*zoom;
 for(let i=0;i<2;i++){const p=f.fighters[i],other=f.fighters[1-i],x=mapX(p.x),y=mapY(p.y),face=b.local===0?p.x>other.x:p.x<other.x,recent=f.events.at(-1),hurt=recent&&f.time-recent.time<.35&&['hit','special'].includes(recent.type)&&recent.actor===1-i,state=hurt?'hurt':['melee','special'].includes(p.action)?'attack':p.action==='disobey'?'sad':p.action==='evade'?'angry':'idle';ChampSprites.draw(c,p.species,ChampSprites.frame(p.species,state,Math.floor(now/(f.sudden?125:250))),x-8*spriteScale,y-12*spriteScale,spriteScale,face);if(p.action==='defend'){c.strokeStyle='#86cbd4';c.lineWidth=3;c.beginPath();c.ellipse(x,y-30*zoom,44*zoom,42*zoom,0,0,Math.PI*2);c.stroke();}if(p.action==='heal'){c.fillStyle='#a6d997';c.fillRect(x-3*zoom,y-75*zoom,6*zoom,20*zoom);c.fillRect(x-10*zoom,y-68*zoom,20*zoom,6*zoom);}}
 for(const p of f.projectiles){const x=mapX(p.x),y=mapY(p.y);c.fillStyle=p.color||'#edcd81';c.save();c.shadowColor=c.fillStyle;c.shadowBlur=12;c.beginPath();c.arc(x,y-31,7+Math.sin(now/60)*2,0,Math.PI*2);c.fill();c.fillStyle='#ffd87c';for(let j=0;j<4;j++){const a=now/100+j*Math.PI/2;c.fillRect(x+Math.cos(a)*12-2,y-33+Math.sin(a)*12,4,4);}c.restore();}if(!b.done){const event=f.events.at(-1);$('battle-log').textContent=event&&f.time-event.time<1.5?(event.type==='special'?Champ.PROFILES[f.fighters[event.actor].species].specialMove.name:t(event.type))+(event.amount?' '+event.amount:''):'';if(f.done&&!b.sent){b.sent=true;if(b.mode==='colosseum')finishBattle(f.winner);else send({type:'DONE',round:b.round});}}}
const peer=new DMNet.LobbyLink(config.server||DMNet.DEFAULT_URL);let battlePet=null,nick=config.nick||'',roomDraft='',passwordDraft='';
function send(m){try{peer.send(m);}catch{notice('connectionLost');}}
function unlockBattle(){for(const p of game.s.pets)p.battleLock=false;}
function disconnect(){peer.close();unlockBattle();battle=null;battlePet=null;}
peer.onchange=()=>{if(screen==='netplay')netMenu();else if(screen==='battle'&&battle?.done&&peer.room?.phase==='result'){const other=peer.room.players.find(p=>p.id!==peer.id),self=peer.room.players.find(p=>p.id===peer.id);if(other?.rematch&&!self?.rematch)$('battle-log').textContent=t('rematchChallenge');}};
peer.onerror=k=>{if(peer.room?.phase==='lobby')unlockBattle();notice(k);};peer.onlost=k=>{unlockBattle();battle=null;battlePet=null;if(screen==='battle'||screen==='netplay'){show('netplay');notice(k);}else notice(k);};
peer.onbattle=m=>{const p=game.get(battlePet);if(!p){send({type:'LEAVE'});return;}startBattle(m.fighters,m.seed,p.instanceId,'netplay',m.local,m.round);};
peer.onresult=m=>{if(battle?.round===m.round){finishBattle(m.winner);}};
function rematch(){const id=battle?.id||battlePet;if(!game.canBattle(id)){notice('needRookie');return;}const fighter=game.fighter(id);battlePet=id;game.get(id).battleLock=true;send({type:'REMATCH',round:peer.round,fighter});if($('rematch'))$('rematch').disabled=true;notice('waiting');}
function netMenu(){screen='netplay';if(peer.status!=='connected'){panel('netplay',`${fighterSelect()}<label>${esc(t('nickname'))}<input id="nick" maxlength="24" value="${esc(nick)}"></label>${btn('connect','connect','primary',peer.status==='connecting')}<p class="muted">${esc(t('serverHint'))}</p>`);$('fighter').onchange=e=>{selected=e.target.value;};on('connect',()=>{nick=$('nick').value.trim();if(!nick)return;config.nick=nick;DMStore.saveSettings(config);peer.connect(nick);});return;}
 if(!peer.room){panel('netplay',`<label>${esc(t('roomName'))}<input id="room-name" maxlength="40" value="${esc(roomDraft)}"></label><label>${esc(t('password'))}<input id="room-password" maxlength="64" type="password" value="${esc(passwordDraft)}"></label><div class="controls">${btn('create','createRoom','primary')}${btn('refresh','refresh')}${btn('disconnect','disconnect')}</div><h3>${esc(t('rooms'))}</h3>${peer.rooms.map((r,i)=>`<div class="room"><span>${esc(r.name)}<small>${esc(r.host)} · ${r.count}/2 ${r.locked?'🔒':''}</small></span>${btn('join-'+i,'joinRoom','',r.count>=2||r.phase!=='lobby')}</div>`).join('')||`<p>${esc(t('noRooms'))}</p>`}`);$('room-name').oninput=e=>roomDraft=e.target.value;$('room-password').oninput=e=>passwordDraft=e.target.value;on('create',()=>send({type:'CREATE',name:roomDraft,password:passwordDraft}));on('refresh',()=>send({type:'LIST'}));on('disconnect',()=>{disconnect();netMenu();});peer.rooms.forEach((r,i)=>on('join-'+i,()=>{if(r.locked){panel('joinRoom',`<label>${esc(t('password'))}<input id="join-pass" type="password" maxlength="64"></label>${btn('join-submit','joinRoom')}`);on('join-submit',()=>send({type:'JOIN',id:r.id,password:$('join-pass').value}));}else send({type:'JOIN',id:r.id,password:''});}));return;}
 const r=peer.room,host=r.host===peer.id,own=r.players.find(p=>p.id===peer.id);panel('netplay',`${r.phase==='lobby'?fighterSelect():''}<h3>${esc(r.name)}</h3>${r.players.map(p=>`<div class="room"><span>${esc(p.nick)} · ${esc(t(p.id===r.host?'hostRole':'challengerRole'))}</span><b>${p.ready?'✓ '+esc(t('ready')):p.rematch?'✓':'—'}</b></div>`).join('')}<div class="controls">${r.phase==='lobby'?btn('ready','ready',own?.ready?'active':'primary')+(host?btn('start','hostStart','',r.players.length!==2||!r.players.every(p=>p.ready)):''):(r.phase==='result'?btn('rematch','rematch','primary',!!own?.rematch):'')}${host&&r.players.length===2?btn('kick','kick','danger',r.phase==='battle'):''}${btn('leave','leave')}</div>`);if($('fighter')){$('fighter').disabled=!!own?.ready;$('fighter').onchange=e=>selected=e.target.value;}on('ready',()=>{if(own?.ready){send({type:'READY',ready:false});unlockBattle();return;}const p=petSelected();if(!game.canBattle(p?.instanceId)){notice('needRookie');return;}const fighter=game.fighter(p.instanceId);battlePet=p.instanceId;p.battleLock=true;send({type:'READY',ready:true,fighter});});on('start',()=>send({type:'START'}));on('leave',()=>{send({type:'LEAVE'});unlockBattle();});on('kick',()=>ask('kickConfirm',()=>{send({type:'KICK',target:r.players.find(p=>p.id!==peer.id).id});show('netplay');},()=>show('netplay')));on('rematch',rematch);if(r.phase==='result'&&r.players.some(p=>p.id!==peer.id&&p.rematch)&&!own?.rematch)notice('rematchChallenge');}
function point(e){const r=$('scene').getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*$('scene').width+camera,y:(e.clientY-r.top)/r.height*320,inside:e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom};}
function hit(p){return [...game.s.pets].reverse().find(d=>!d.battleLock&&Math.abs(d.x-p.x)<42&&p.y>d.y-75&&p.y<d.y+10);}
function startGesture(e,item=null){if(screen!=='home'||gesture||deleting)return;if(e.button!==0&&e.pointerType==='mouse')return;e.preventDefault();const p=point(e),pet=!item&&!tool?hit(p):null;gesture={id:e.pointerId,el:e.currentTarget,item:item||tool,pet:pet?.instanceId,startX:e.clientX,startY:e.clientY,cam:camera,moved:false,point:p,original:pet?{x:pet.x,y:pet.y}:null};if(pet){pet.dragging=true;selected=pet.instanceId;}e.currentTarget.setPointerCapture(e.pointerId);}
$('scene').addEventListener('pointerdown',e=>startGesture(e));document.addEventListener('pointermove',e=>{const g=gesture;if(!g||g.id!==e.pointerId)return;e.preventDefault();g.point=point(e);g.moved||=Math.hypot(e.clientX-g.startX,e.clientY-g.startY)>5;if(g.pet){const p=game.get(g.pet),dx=(e.clientX-g.startX)/$('scene').clientWidth*$('scene').width*PET_DRAG_GAIN;p.x=Math.max(24,Math.min(Champ.worldWidth-24,g.original.x+dx+(camera-g.cam)));p.y=Math.max(160,Math.min(290,g.point.y+25));}else if(!g.item)camera=clampCamera(g.cam-(e.clientX-g.startX)/$('scene').clientWidth*$('scene').width*DRAG_GAIN);},{passive:false});
function endGesture(e,cancel=false){const g=gesture;if(!g||g.id!==e.pointerId)return;gesture=null;try{g.el.releasePointerCapture(g.id);}catch{}if(g.pet){const p=game.get(g.pet);if(p){if(cancel){p.x=g.original.x;p.y=g.original.y;p.dragging=false;}else game.drop(p.instanceId,p.x,p.y);}hudPets();}else if(g.item&&!cancel){const p=point(e);if(p.inside){if(g.item==='meat')game.food(p.x,p.y);if(g.item==='med'){const pet=hit(p);if(pet){if(game.medicine(pet.instanceId))fx={kind:'med',x:pet.x,y:pet.y,start:performance.now()};else{pet.refuseUntil=performance.now()+900;notice('noMedicine',{name:petName(pet)});}}}if(g.item==='clean'){game.clean(p.x,p.y);fx={kind:'clean',x:p.x,y:p.y,start:performance.now()};}tool=null;}else if(!g.moved){tool=g.item;notice('dragHint');}document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));}save();}
document.addEventListener('pointerup',e=>endGesture(e));document.addEventListener('pointercancel',e=>endGesture(e,true));$('scene').addEventListener('wheel',e=>{e.preventDefault();camera=clampCamera(camera+e.deltaX+e.deltaY);},{passive:false});
function clampCamera(v){return Math.max(0,Math.min(Champ.worldWidth-$('scene').width,v));}
function drawWorld(now){const cv=$('scene'),h=320,w=Math.round(cv.clientWidth/cv.clientHeight*h);if(w<=0||!Number.isFinite(w))return;if(cv.width!==w||cv.height!==h){cv.width=w;cv.height=h;}camera=clampCamera(camera);const c=cv.getContext('2d');c.imageSmoothingEnabled=false;c.clearRect(0,0,w,h);c.save();c.translate(-camera,0);for(let i=0;i<7;i++)if(i*300<camera+w&&(i+1)*300>camera)ChampArt.cage(c,i,t);for(const d of game.s.waste)ChampArt.poop(c,d.x,d.y);for(const f of game.s.food){if(f.bites>0&&game.get(f.reserved))continue;const fraction=[1,.66,.33][Math.min(2,Math.floor(f.bites/.6))];if(images.meat.complete)c.drawImage(images.meat,32*(1-fraction),0,32*fraction,32,f.x-28+56*(1-fraction),f.y-44,56*fraction,56);}
 for(const p of game.s.pets){let alpha=deleting?.id===p.instanceId?Math.max(0,1-(now-deleting.start)/1500):1;c.save();c.globalAlpha=alpha;const x=p.x-32+(p.refuseUntil>now?Math.sin(now/35)*5:0),y=p.y-64;if(p.speciesId===null){c.save();c.translate(p.x,p.y);c.rotate(Math.sin(now/130)*.08);if(eggImage(p).complete)c.drawImage(eggImage(p),-32,-64,64,64);c.restore();}else{{const state=p.refuseUntil>now?'refuse':p.action==='sleep'?'sleep':p.action==='eat'?'eat':p.actionUntil>game.s.clock?'train':p.action==='walk'?'walk':'idle',tick=state==='eat'?Math.floor(now/220):state==='sleep'?Math.floor(now/520):state==='train'?ChampArt.trainingStep(p,game.s.clock):Math.floor(now/380);ChampSprites.draw(c,p.speciesId,ChampSprites.frame(p.speciesId,state,tick),x,y,4,p.face<0,alpha);}if(p.evolution&&game.s.clock<p.evolution.until){c.strokeStyle='#f2e39b';c.lineWidth=3;const progress=1-(p.evolution.until-game.s.clock)/2.6;c.beginPath();c.ellipse(p.x,p.y-32,40+progress*40,40+progress*20,0,0,Math.PI*2);c.stroke();}if(p.action==='sleep'){c.fillStyle='#e5edce';c.textAlign='center';for(let i=0;i<3;i++){let q=(now/1800+i/3)%1;c.globalAlpha=alpha*Math.sin(q*Math.PI);c.font=(18-q*6)+'px Pixels';c.fillText(i?'z':'Z',p.x+16+q*20,p.y-62-q*40);}c.globalAlpha=alpha;}if(p.actionUntil>game.s.clock)ChampArt.training(c,p,game.s.clock);c.font='15px Pixels';c.textAlign='center';c.fillStyle='#fff3bf';c.strokeStyle='#314b36';c.lineWidth=3;const label=p.sick||p.injured?'✚ !':p.fatigue>=95?'Zzz':p.hunger<20?'!':'';if(label){c.strokeText(label,p.x,y-8);c.fillText(label,p.x,y-8);}}
 const meal=game.s.food.find(f=>f.reserved===p.instanceId&&f.bites>0);if(meal&&images.meat.complete){const fraction=[1,.66,.33][Math.min(2,Math.floor(meal.bites/.6))];c.drawImage(images.meat,32*(1-fraction),0,32*fraction,32,p.x+(p.face<0?-46:5)+48*(1-fraction),p.y-43,48*fraction,48);}c.font='12px Pixels';c.textAlign='center';c.fillStyle='#f2ebc3';c.strokeStyle='#2a4732';c.lineWidth=3;c.strokeText(petName(p),p.x,p.y+19);c.fillText(petName(p),p.x,p.y+19);c.restore();}
 if(fx&&now-fx.start<1300){const phase=(now-fx.start)/1300;if(fx.kind==='med'){if(images.med.complete)c.drawImage(images.med,fx.x-18,fx.y-65-phase*20,36,36);c.fillStyle='#b3e99f';c.fillRect(fx.x+25,fx.y-50-phase*30,5,20);c.fillRect(fx.x+18,fx.y-43-phase*30,20,5);}else{const x=fx.x-30+phase*60;c.fillStyle='#e4c58a';c.fillRect(x,fx.y-48,5,42);c.fillStyle='#c8bf79';c.fillRect(x-12,fx.y-10,30,12);}}
 if(gesture?.item&&gesture.point.inside){const p=gesture.point;if(images[gesture.item]?.complete){c.globalAlpha=.7;c.drawImage(images[gesture.item],p.x-16,p.y-16,32,32);}}
 c.restore();if(deleting&&now-deleting.start>=1500){game.delete(deleting.id);deleting=null;save();hudPets();notice('deleted');}}
function drawCards(now){document.querySelectorAll('canvas[data-species],canvas[data-pet]').forEach(cv=>{const p=cv.dataset.pet?game.get(cv.dataset.pet):null,id=p?p.speciesId:Number(cv.dataset.species),c=cv.getContext('2d');c.clearRect(0,0,cv.width,cv.height);if(id===null){if(eggImage(p).complete)c.drawImage(eggImage(p),cv.width/2-32,10,64,64);}else ChampSprites.draw(c,id,ChampSprites.frame(id,'idle',Math.floor(now/500)),cv.width/2-32,8,4,false);});}
let last=performance.now(),lastAuto=last,lastHUD=last;
function tick(now){const dt=Math.max(0,(now-last)/1000);last=now;if(playing){game.advance(dt);for(const e of game.events.splice(0)){notice(e.key,{name:e.name});if(e.key==='evolved')sound(true);}}if(fade<1){fade=unitVolume((now-fadeStart)/1000,0);music.menu.volume=unitVolume(unitVolume(config.volume)*fade,0);if(musicMode==='menu'&&musicStarted&&music.menu.paused&&config.volume>0)music.menu.play().catch(()=>{});}if(screen==='home'){if(gesture&&(gesture.pet||gesture.item)&&gesture.point.inside){const x=gesture.point.x-camera,w=$('scene').width,dir=x<35?-1:x>w-35?1:0,oldCamera=camera;camera=clampCamera(camera+dir*Math.min(dt,.1)*EDGE_PAN_SPEED);const shift=camera-oldCamera;gesture.point.x+=shift;if(gesture.pet){const p=game.get(gesture.pet);if(p)p.x=Math.max(24,Math.min(Champ.worldWidth-24,p.x+shift));}}drawWorld(now);}else if(screen==='battle')drawBattle(now);else drawCards(now);if(now-lastHUD>1000){hudPets();if(screen==='status'){status();drawCards(now);}updateTips();lastHUD=now;}if(now>noticeEnd){$('notice').style.opacity=0;$('panel-notice')?.remove();}if(playing&&now-lastAuto>=30000){save();lastAuto=now;}requestAnimationFrame(tick);}
window.addEventListener('beforeunload',()=>{if(playing)save();peer.close();});window.addEventListener('pagehide',()=>{if(playing)save();});show('menu');requestAnimationFrame(tick);
})();
