'use strict';
(function(root){
const PROTOCOL=4;
const DEFAULT_URL='wss://digital-beasts-championship.armster1991.workers.dev/ws';
class LobbyLink{
 constructor(url=DEFAULT_URL){this.url=url;this.ws=null;this.id=null;this.room=null;this.rooms=[];this.status='disconnected';this.round=null;this.onchange=()=>{};this.onbattle=()=>{};this.onresult=()=>{};this.onlost=()=>{};this.onerror=()=>{};}
 connect(nick){this.close();this.status='connecting';this.onchange();const ws=new WebSocket(this.url);this.ws=ws;const timer=setTimeout(()=>{if(this.ws===ws&&this.status!=='connected'){this.onerror('lobbyUnavailable');this.close();this.onchange();}},15000);ws.onopen=()=>{if(this.ws!==ws)return;clearTimeout(timer);this.status='connected';this.send({type:'HELLO',nick});this.onchange();};ws.onmessage=e=>{if(this.ws!==ws||e.data==='pong')return;try{if(typeof e.data!=='string'||e.data.length>20000)throw Error();const m=JSON.parse(e.data);if(m.v!==PROTOCOL)throw Error('wrongVersion');if(m.type==='WELCOME')this.id=m.id;else if(m.type==='LIST'){this.rooms=m.rooms||[];this.onchange();}else if(m.type==='ROOM'){this.room=m.room;this.onchange();}else if(m.type==='LEFT'){this.room=null;this.round=null;this.onlost(m.key||'roomClosed');this.onchange();}else if(m.type==='OPPONENT_LEFT'){this.round=null;this.onlost(m.key||'opponentLeft');this.onchange();}else if(m.type==='BATTLE_START'){if(!Array.isArray(m.fighters)||m.fighters.length!==2||![0,1].includes(m.local)||!Number.isInteger(m.seed)||typeof m.round!=='string')throw Error();this.round=m.round;this.onbattle(m);}else if(m.type==='RESULT'){if(m.round===this.round&&[0,1].includes(m.winner))this.onresult(m);}else if(m.type==='ERROR')this.onerror(m.key);else throw Error();}catch(e){this.onerror(e.message==='wrongVersion'?'wrongVersion':'badMessage');this.close();this.onlost('connectionLost');}};ws.onclose=()=>{clearTimeout(timer);if(this.ws!==ws)return;this.ws=null;this.status='disconnected';this.room=null;this.onlost('connectionLost');this.onchange();};ws.onerror=()=>{if(this.ws===ws)this.onerror('lobbyUnavailable');};}
 send(m){if(this.ws?.readyState!==WebSocket.OPEN)throw Error('notConnected');this.ws.send(JSON.stringify({v:PROTOCOL,...m}));}
 close(){if(this.ws){this.ws.onclose=null;this.ws.close();}this.ws=null;this.room=null;this.round=null;this.id=null;this.status='disconnected';}
}
root.DMNet={LobbyLink,PROTOCOL,DEFAULT_URL};
})(globalThis);
