import {LobbyCore,PROTOCOL,ROSTER_VERSION} from './core.mjs';
export default {async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/'||u.pathname==='/health')return Response.json({service:'Digital Beasts Championship Lobby',protocol:PROTOCOL,roster:ROSTER_VERSION,configured:!!env.LOBBY},{headers:{'Cache-Control':'no-store'}});if(u.pathname!=='/ws'||request.headers.get('Upgrade')?.toLowerCase()!=='websocket')return new Response('Not found',{status:404});const allowed=(env.ALLOWED_ORIGINS||'https://armster1991.github.io,null').split(',');if(!allowed.includes(request.headers.get('Origin')))return new Response('Origin denied',{status:403});if(!env.LOBBY)return new Response('Lobby binding missing',{status:503});return env.LOBBY.get(env.LOBBY.idFromName('digital-beasts-championship-v1')).fetch(request);}};
export class LobbyServer{
 constructor(ctx,env){this.ctx=ctx;this.queue=Promise.resolve();this.ready=ctx.blockConcurrencyWhile(async()=>{const sockets=ctx.getWebSockets();this.sockets=new Map();const clients=[];for(const ws of sockets){try{const c=ws.deserializeAttachment();if(c?.id){this.sockets.set(c.id,ws);clients.push(c);}}catch{ws.close(1011,'Invalid session');}}this.core=new LobbyCore({rooms:await ctx.storage.get('rooms')||[],clients});await this.flush();});if(typeof WebSocketRequestResponsePair!=='undefined')ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair('ping','pong'));}
 async flush(){await this.ctx.storage.put('rooms',[...this.core.rooms.values()]);for(const [id,ws] of this.sockets){const c=this.core.clients.get(id);if(c)ws.serializeAttachment(c);}for(const {id,message} of this.core.out.splice(0)){try{this.sockets.get(id)?.send(JSON.stringify(message));}catch{}}}
 serial(fn){const task=this.queue.then(async()=>{await this.ready;await fn();await this.flush();});this.queue=task.catch(()=>{});return task;}
 async fetch(request){let result;await this.serial(async()=>{const id=crypto.randomUUID();try{this.core.connect(id,request.headers.get('CF-Connecting-IP')||'unknown');}catch(e){result=new Response(e.message,{status:429});return;}const pair=new WebSocketPair(),client=pair[0],server=pair[1];this.ctx.acceptWebSocket(server);this.sockets.set(id,server);result=new Response(null,{status:101,webSocket:client});});return result;}
 async webSocketMessage(ws,data){await this.serial(async()=>{const id=ws.deserializeAttachment()?.id;if(!id)return;try{if(typeof data!=='string'||data.length>4096)throw Error('badMessage');await this.core.handle(id,JSON.parse(data));}catch(e){this.core.error(id,e.message);}});}
 async webSocketClose(ws){await this.serial(async()=>{const id=ws.deserializeAttachment()?.id;if(id){this.core.disconnect(id);this.sockets.delete(id);}try{ws.close();}catch{}});}
 async webSocketError(ws){return this.webSocketClose(ws);}
}
