import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {LobbyCore,PROTOCOL,ROSTER_VERSION,fight} from '../server/core.mjs';
const require=createRequire(import.meta.url),P=require('../profiles.js');
const css=fs.readFileSync(new URL('../style.css',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const net=fs.readFileSync(new URL('../netplay.js',import.meta.url),'utf8');
const i18n=fs.readFileSync(new URL('../champ-i18n.js',import.meta.url),'utf8');
const serverProfiles=fs.readFileSync(new URL('../server/profiles.js',import.meta.url),'utf8');
const clientProfiles=fs.readFileSync(new URL('../profiles.js',import.meta.url),'utf8');
assert.equal(P.length,282);
assert.equal(ROSTER_VERSION,P.length);
assert.equal(serverProfiles,clientProfiles);
assert(css.includes('portrait-first mobile layout; no orientation lock'));
assert(!css.includes('#device{display:none}'));
assert(css.includes('#rotate-device{display:none!important}'));
assert(css.includes('#habitat{grid-template-rows:34px auto 45px minmax(88px,1fr)'));
assert(css.includes('#world{height:clamp(235px,46dvh'));
assert(app.includes("zoom=mobilePortrait?1.10:1"));
assert(app.includes("toLocalX(f.fighters[b.local].x)"));
assert(net.includes('this.serverRoster=Number.isInteger(m.roster)?m.roster:null'));
assert(app.includes("notice('serverRosterOutdated')"));
assert(i18n.includes('serverRosterOutdated'));
let now=1000,validated=0;
for(const p of P.filter(x=>x.speciesId>=134&&x.stage>=3)){
 const core=new LobbyCore({now:()=>now});
 core.connect('a','a');
 assert.equal(core.out[0].message.roster,282);
 await core.handle('a',{v:PROTOCOL,type:'HELLO',nick:'a'});
 await core.handle('a',{v:PROTOCOL,type:'CREATE',name:'r',password:''});
 const b=[0,12,24,80,120,160,200,240][p.stage],g1=Math.floor(b*.6),g2=b-g1;
 const stats={...p.stats,attack:p.stats.attack+g1,speed:p.stats.speed+g2};
 await core.handle('a',{v:PROTOCOL,type:'READY',ready:true,fighter:{species:p.speciesId,stats}});
 const result=fight({species:p.speciesId,stats},{species:2,stats:P[2].stats},p.speciesId+5000);
 assert([0,1].includes(result.winner));
 validated++;
}
const galemon=P.find(x=>x.name==='Galemon');
assert.equal(galemon.speciesId,238);
assert.equal(galemon.stage,4);
console.log(`PASS v0.4.4: portrait-first mobile, local-player battle camera, roster handshake 282, Galemon ${galemon.speciesId}, ${validated} new battle-capable Digimon validated in READY + authoritative fight.`);
