const assert=require('node:assert/strict'),C=require('../engine'),B=require('../battle'),fs=require('fs'),path=require('path');
assert.equal(fs.readFileSync(path.join(__dirname,'../battle.js'),'utf8'),fs.readFileSync(path.join(__dirname,'../server/battle.js'),'utf8'));
// An untrained Rookie still wins most early fights, but loses a meaningful amount of HP.
let wins=0,hp=0,n=0;for(let round=1;round<=20;round++)for(let seed=1;seed<=20;seed++){const enemy=C.colosseum[round-1],s=new B.BattleSim([{species:19,stats:C.PROFILES[19].stats},{species:enemy.id,stats:C.PROFILES[enemy.id].stats}],seed,{colosseumRound:round});while(!s.done)s.step();wins+=s.winner===0;hp+=s.fighters[0].hp/s.fighters[0].stats.hp;n++;assert(s.time<=B.MAX_TIME);}assert(wins/n>.7&&wins/n<.98);assert(hp/n<.5);
// Retreat at corners must use the free vertical/horizontal direction, not remain pinned.
for(const [x,y,bx,by]of [[30,65,100,100],[570,65,500,100],[30,270,100,240],[570,270,500,240],[30,160,100,160]]){const a={x,y};for(let i=0;i<10;i++)B.retreat(a,{x:bx,y:by},3);assert(Math.hypot(a.x-x,a.y-y)>10);assert(a.x>=30&&a.x<=570&&a.y>=65&&a.y<=270);}
const fighters=[{species:2,stats:C.PROFILES[2].stats},{species:18,stats:C.PROFILES[18].stats}];
const sd=new B.BattleSim(fighters,42);sd.time=89.9;sd.fighters.forEach(f=>{f.cooldown=1;f.guardUntil=94;f.disobeyUntil=0;});sd.step();assert(sd.sudden);assert.equal(sd.time,90);assert.equal(sd.fighters[0].cooldown,.8);assert.equal(sd.fighters[0].guardUntil,92);assert(sd.events.some(e=>e.type==='suddenDeath'));
const normal=new B.BattleSim(fighters,1),sudden=new B.BattleSim(fighters,1);normal.rng=sudden.rng=()=>.5;sudden.sudden=true;normal.damage(0,1,false);sudden.damage(0,1,false);assert(sudden.events.at(-1).amount>=normal.events.at(-1).amount);
const d1=new B.BattleSim(fighters,1),d2=new B.BattleSim(fighters,1);d1.rng=d2.rng=()=>.05;d2.sudden=true;d1.damage(0,1,false);d2.damage(0,1,false);assert.equal(d1.events.at(-1).type,'miss');assert.equal(d2.events.at(-1).type,'hit');
let max=0,sdCount=0,timeouts=0;for(let id=0;id<C.catalog.length;id++)for(let seed=1;seed<=10;seed++){const a={species:id,stats:C.PROFILES[id].stats},b={species:(id+3)%134,stats:C.PROFILES[(id+3)%134].stats},s=new B.BattleSim([a,b],seed);while(!s.done)s.step();max=Math.max(max,s.time);sdCount+=s.sudden;timeouts+=s.events.some(e=>e.type==='timeout');assert(s.time<=135);assert(s.fighters.every(f=>f.hp>=0));}
console.log(JSON.stringify({tests:'PASS: balance, corner steering, 90s transition, action speed, reduced armor/dodge, shared Worker',earlyWins:wins/n,earlyRemainingHP:hp/n,rosterFights:1340,maxSeconds:max,suddenFights:sdCount,timeouts},null,2));

let tankSudden=0,tankTimeout=0;for(let id=0;id<134;id++){const p=C.PROFILES[id],budget=C.budget(p.stage),f={species:id,stats:{...p.stats,hp:p.stats.hp+Math.floor(budget*.6)*5,defense:p.stats.defense+Math.floor(budget*.4)}};const s=new B.BattleSim([f,f],45);while(!s.done)s.step();tankSudden+=s.sudden;tankTimeout+=s.events.some(e=>e.type==='timeout');assert(s.time<=135);}assert(tankSudden>0);console.log('PASS durable mirrors:',{battles:134,sudden:tankSudden,safetyTimeouts:tankTimeout});
